name: Build project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'

jobs:
  composer-project:
    name: PHP ${{ matrix.php }}
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        php: [8.1, 8.2, 8.3]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v2
        with:
          path: template-project

      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Create Drupal project
        run: |
          composer create-project php-tuf/drupal-project --repository '{"type": "path", "url": "template-project", "options": {"symlink": false}}' --stability=dev -vvv

      - name: Install modules and themes
        run: composer -vvv require drupal/address
        working-directory: drupal-project
